{{- if and .Values.navidrome.persistence.enabled (not .Values.navidrome.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "navidrome.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "navidrome.name" . }}
    helm.sh/chart: {{ include "navidrome.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: app
  annotations:
    helm.sh/resource-policy: keep
  {{- with .Values.navidrome.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.navidrome.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.navidrome.persistence.size | quote }}
  {{- with .Values.navidrome.persistence.storageClass }}
  {{- if (eq "-" .) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ . }}"
  {{- end }}
  {{- end }}
{{- end }}